"""
Domain Models — Pydantic models and enums for the video pipeline.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class JobStatus(str, Enum):
    """Status of an async video generation job."""
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class GenerateRequest(BaseModel):
    """Request body for video generation (API + webhook)."""
    script: Optional[str] = Field(
        default=None,
        description="The voiceover script text (full content, not a file path). Optional if 'topic' is provided.",
    )
    topic: Optional[str] = Field(
        default=None,
        description="Video topic — GPT-4o will auto-generate the voiceover script. Alternative to 'script'.",
    )
    script_style: str = Field(
        default="informative and engaging",
        description="Writing style for AI script generation (only used with 'topic')",
    )
    script_minutes: int = Field(
        default=10,
        description="Target video length in minutes (only used with 'topic')",
    )
    title: str = Field(
        default="AI Generated Video",
        description="YouTube video title",
    )
    description: str = Field(
        default="Generated by AI Video Agent",
        description="YouTube video description",
    )
    tags: list[str] = Field(
        default=["AI", "automation"],
        description="YouTube tags/keywords",
    )
    privacy: str = Field(
        default="private",
        description="YouTube privacy: private, unlisted, or public",
    )
    skip_upload: bool = Field(
        default=True,
        description="Skip YouTube upload (just generate the video file)",
    )
    skip_images: bool = Field(
        default=False,
        description="Skip image generation (use existing images)",
    )


class JobInfo(BaseModel):
    """Job status and result tracking."""
    job_id: str
    status: JobStatus
    created_at: str
    completed_at: Optional[str] = None
    error: Optional[str] = None
    result: Optional[dict] = None
    request: Optional[dict] = None
